String lightMap =
    '[{"stylers":[{"visibility":"simplified"}]},{"featureType":"administrative","stylers":[{"color":"#7393ab"}]},{"featureType":"landscape","stylers":[{"color":"#dae6eb"}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#c6e8b3"}]},{"featureType":"poi","elementType":"labels","stylers":[{"color":"#7393ab"},{"visibility":"off"}]},{"featureType":"poi.business","stylers":[{"visibility":"simplified"}]},{"featureType":"poi.school","stylers":[{"visibility":"simplified"}]},{"featureType":"road","stylers":[{"color":"#e4f0f7"}]},{"featureType":"road","elementType":"geometry","stylers":[{"color":"#e4f0f7"},{"visibility":"on"}]},{"featureType":"road","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"transit.line","stylers":[{"color":"#cccccc"}]},{"featureType":"water","stylers":[{"color":"#a6cbe3"}]},{"featureType":"water","elementType":"labels","stylers":[{"visibility":"off"}]}]';

String darkMap =
    '[{"stylers":[{"visibility":"simplified"}]},{"featureType":"administrative","stylers":[{"color":"#dfdfdf"}]},{"featureType":"landscape","stylers":[{"color":"#3e4f5c"}]},{"featureType":"poi","elementType":"geometry","stylers":[{"color":"#0e8d6f"}]},{"featureType":"poi","elementType":"labels","stylers":[{"color":"#cfd8dc"},{"visibility":"off"}]},{"featureType":"poi.business","stylers":[{"visibility":"simplified"}]},{"featureType":"poi.school","stylers":[{"visibility":"simplified"}]},{"featureType":"road","stylers":[{"color":"#4b5f70"}]},{"featureType":"road","elementType":"geometry","stylers":[{"color":"#4b5f70"},{"visibility":"on"}]},{"featureType":"road","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"transit","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"transit.line","stylers":[{"color":"#999999"}]},{"featureType":"water","stylers":[{"color":"#2a353e"}]},{"featureType":"water","elementType":"labels","stylers":[{"visibility":"off"}]}]';

String lightMap2 =
    '[{"featureType":"administrative","elementType":"labels","stylers":[{"hue":"#ff0000"}]},{"featureType":"administrative","elementType":"labels.text.fill","stylers":[{"color":"#444444"}]},{"featureType":"administrative.land_parcel","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"landscape","stylers":[{"color":"#f2f2f2"}]},{"featureType":"poi","stylers":[{"visibility":"off"}]},{"featureType":"poi","elementType":"geometry","stylers":[{"hue":"#00ffaa"},{"saturation":"26"},{"lightness":"68"},{"visibility":"on"}]},{"featureType":"poi","elementType":"labels","stylers":[{"hue":"#00acff"},{"visibility":"simplified"}]},{"featureType":"poi","elementType":"labels.icon","stylers":[{"hue":"#00a6ff"},{"saturation":"-100"},{"lightness":"-6"}]},{"featureType":"poi","elementType":"labels.text","stylers":[{"hue":"#00daff"},{"saturation":"-100"},{"visibility":"off"}]},{"featureType":"poi.park","stylers":[{"hue":"#00ff78"},{"saturation":"11"},{"lightness":"-5"},{"gamma":"1.06"}]},{"featureType":"road","stylers":[{"saturation":-100},{"lightness":45}]},{"featureType":"road.arterial","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"road.arterial","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"road.highway","stylers":[{"visibility":"simplified"}]},{"featureType":"road.highway","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"road.local","stylers":[{"visibility":"off"}]},{"featureType":"road.local","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"transit","stylers":[{"visibility":"off"}]},{"featureType":"water","stylers":[{"hue":"#00acff"},{"visibility":"on"}]},{"featureType":"water","elementType":"geometry","stylers":[{"visibility":"on"}]},{"featureType":"water","elementType":"labels","stylers":[{"visibility":"on"}]},{"featureType":"water","elementType":"labels.text","stylers":[{"hue":"#0061ff"},{"visibility":"on"}]}]';

String darkMap2 =
    '[{"stylers":[{"hue":"#00ffee"},{"saturation":20},{"invert_lightness":true},{"lightness":50},{"gamma":0.4}]},{"elementType":"geometry","stylers":[{"visibility":"simplified"}]},{"elementType":"labels","stylers":[{"visibility":"on"}]},{"featureType":"administrative","stylers":[{"color":"#ffffff"},{"visibility":"simplified"}]},{"featureType":"administrative.land_parcel","elementType":"geometry.stroke","stylers":[{"visibility":"simplified"}]},{"featureType":"administrative.land_parcel","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"landscape","stylers":[{"color":"#405769"}]},{"featureType":"poi","elementType":"labels.text","stylers":[{"visibility":"off"}]},{"featureType":"road.arterial","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"road.highway","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"road.local","stylers":[{"visibility":"off"}]},{"featureType":"road.local","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"water","elementType":"geometry.fill","stylers":[{"color":"#232f3a"}]}]';
